language: go
go:
- 1.10.x
- 1.11.x

os:
- linux
- osx
dist: trusty
sudo: false
install: true
script:
- go get golang.org/x/tools/cmd/cover/...
- go get github.com/mattn/goveralls/...
- env GO111MODULE=on go build
- env GO111MODULE=on go test -v -covermode=count -coverprofile=coverage.out ./...
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
  
env:
  global:
    secure: MRZFXkbbzckI3jl3sP3zkjt6Ezy6pX7vAthXKzF8pIvysXCzDm5Z7AlISWTk7PCcErH2OdndsGmUI6WvPJjm/TZxFCyRgkbzfxGbmFi6Z2b/Ib5fj2SEgdLUeKnofi7oRx27kzEG4wlCxbOspUedFL5naORvGUkYeGVtIs7xhhQHmJnEIBfe1Z4KGUmCmKjp1RP0uutSHAsmB4umK8CtYFbchfohUd9OGCPQo5ioanZyhDCv1DnZh4b3oWYf08oyTojEM3IrpmwKW6HY9Pywq2vkGo1IcpnoEqB+b+RtGrzdgrXP7rPY9I7V8Y6UpoD5zDWRCGpXJTdq6eVuo0eA5u74XKiWoSkffw9cOSqBxNDTk9SinuqXck+ybr/TWqoqSmdcvC//VEFrXmggqJtdRLXOSv8g+kZcHmUAJtVoeqx0n5hQcMj0Nof85greMKkSwXJ9ccHDL4sZjtFsR7aKcJv0Euo+6ib/kNiQkAbfWA93iDLxUIb0enzPPn/AK+fcGH0GA7epF8RHGm7xKmlv+OhbPQi6Pnh7JTJ/ATYJLenYYOs+Ucx/ygXL5lca6UF+YqFarIDrk3qZGrzkDzItjL8X3BgLyC7NTODsEFJSvZg27EGXy0IaZ6dBFrD10h/ESzzwrQ1Y3D2E8jpMToHqSpw23URbdOXrm4d8BY7c7ac=
