version: "3.3"
services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "127.0.0.1:27017:27017"
  mysql:
    image: "mysql:latest"
    container_name: "mysql"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "test_pass" # TODO: Change this
      MYSQL_USER: "test"
      MYSQL_PASS: "pass"
