version: "3.7"
services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    networks:
      - dev
    ports:
      - "27017:27017"
    expose:
      - 27017

  logs-converter:
    restart: unless-stopped
    container_name: logs-converter
    networks:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
     
    depends_on:
      - mongo
    volumes:
      - ./mounts/logs-converter/testdata/:/testdata/

networks:
  dev:
    driver: bridge

volumes:
  logs-converter: